services:
  redis:
    image: "redis:7.2-alpine"
    restart: "always"
    volumes:
      - "redis-data:/data"
  postgres:
    image: "postgres:16.3-alpine"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "very_hard_password"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  migrations:
    build:
      context: ..
      dockerfile: "deploy/telegram.Dockerfile"
      target: base
    restart: "on-failure"
    depends_on:
      - postgres
    volumes:
      - "../alembic.ini:/app/alembic.ini"
      - "../.env:/app/.env"
      - "../config:/app/config/"
      - "../src:/app/src/"
    entrypoint: [ "poetry", "run", "alembic", "upgrade", "head" ]
  bot:
    restart: "always"
    build:
      context: ..
      dockerfile: "deploy/telegram.Dockerfile"
    depends_on:
      - postgres
      - redis
      - migrations


volumes:
  redis-data:
  postgres-data:
