default:
  postgres:
    username: "postgres"
    password: "very_hard_password"
development:
  telegram:
    bot_token: "0123456789:development"
production:
  telegram:
    bot_token: "9876543210:production"
